### ISSUE TITLE
Small bug with relational division

### ISSUE THREAD

**Issue by ghost** [dbis-uibk/relax#124]
Hello,

thank you very much for RelaX. It's a great tool!

Unfortunately there seems to be a small bug with division. Steps to reproduce:

1. Paste this to Group Editor and click to use it in editor:

group: "Test"

R = {
Person:string, Pet:string
Alice, Cat
Alice, Dog
Bob, Dog
}

S = {
Pet:string
Cat
Dog
}

2. Try the expression **R ÷ S**. The result has only one row: _Alice_. Fine!

3. Go back to Group Editor and change the name of _Bob_ to _Cat_.

4. Try the expression **R ÷ S** again. The result now has an **additional** row: _Cat_. Why?

This seems to be a bug.

Kind regards
Rainer

**Comment by r-prem** [comment]
Fixed with [454bcc](https://github.com/dbis-uibk/relax/commit/454bcc9d164abbb01f20bc550f1ba4021e907dd1)

**Comment by Rainer012** [comment]
Cool. Thank you very much!

**Comment by ghost** [comment]
Thank you very much! But I'm afraid, the bug still exists. I can still reproduce it in the online version of RelaX.

**Comment by r-prem** [comment]
@Rainer012 Haven’t made a new version yet. It’s been fixed in the code. Will reply when a new version has been created.

**Comment by ghost** [comment]
Ah, got it. Thanks again!

**Comment by r-prem** [comment]
@Rainer012 New version is up.

**Comment by ghost** [comment]
Yes, now it's fixed. Thank you very much!
