### ISSUE TITLE
Division is not working properly

### ISSUE THREAD

**Issue by pcgotan** [dbis-uibk/relax#131]
C = {
a:number, b:number
1,5
1,6
5,6
}

D = {
b:number
5
6
}

C / D returns 
{
  1
  5
} 
which is wrong 

it should return 
{
1
}

**Comment by enplotz** [comment]
This is caused by #120 and probably fixed by #129. You can rewrite the division equivalently as `π a (C) - π a ((π a C ⨯ D) - C)` (which still gives the incorrect result of `1,5`).
You can then observe the inner difference `(π a C ⨯ D) - C` returning an empty set, which results in the outer difference doing nothing.

**Comment by dtabass** [comment]
Division is still not fixed.  The difference issue persists.  Is anyone working on it?  It bit my Intro to DB class students this quarter, and it would be great to get it resolved.  (I'm not sure if/who/etc works on this code these days.)

**Comment by r-prem** [comment]
Fixed with [454bcc](https://github.com/dbis-uibk/relax/commit/454bcc9d164abbb01f20bc550f1ba4021e907dd1)
