### ISSUE TITLE
[Test] Join symbol changes in comment mode

### ISSUE THREAD

**Issue by evazangerle** [dbis-uibk/relax#85]
The join symbols are different in "normal" and comment mode - this shouldn't be the case:
![image](https://user-images.githubusercontent.com/10127753/79198619-0e356180-7e34-11ea-8930-dd4eb95b3653.png)

**Comment by michaelrampl** [comment]
probably fixed with c3c6a7cae434bd55deb1403a9af12248759525ca

**Comment by evazangerle** [comment]
Bug still present in current version: 
![image](https://user-images.githubusercontent.com/10127753/79585881-b7988380-80d0-11ea-9a51-c844e6a2fca1.png)

**Comment by r-prem** [comment]
Seems to be working fine now, see attached screen shot. Tested using Chrome, Safari and Firefox on iOS devices. If this still persists on other devices please share more details. Thank you.
![Screenshot 2022-07-22 at 14 17 45](https://user-images.githubusercontent.com/92574486/180437765-14d79f73-4604-4084-94b2-8a45ad95e11b.png)
